### ISSUE TITLE
Errore nella compilazione

### ISSUE THREAD

**Issue by danimog** [ggentili/Italia-Design-Jekyll-Theme#1]
Ciao,
intanto ti ringrazio per aver condiviso il tuo progetto.
Ho provato a compilarlo con jekyll ma mi restituisce l'errore sotto.
I passi che ho fatto:
- git clone del tuo progetto
- cd nella cartella progetto
- build del progetto
Sbaglio qualcosa?

Grazie!

[!] There was an error parsing `Gemfile`: There are no gemspecs at /Users/..../Italia-Design-Jekyll-Theme. Bundler cannot continue.

 #  from /Users/..../Italia-Design-Jekyll-Theme/Gemfile:2
 #  -------------------------------------------
 #  source "https://rubygems.org"
 >  gemspec
 #  
 #  -------------------------------------------

**Comment by ggentili** [comment]
prova a rimuovere Gemfile
